### ISSUE TITLE
Error compiling for ESP32

### ISSUE THREAD

**Issue by ELNAHUAL** [WeekendWarrior1/XTronical_XT_DAC_Audio_Mirror#1]
Every time I try to use tis library I got the "Error compiling for board ESP32 Dev Module" it doesn't matter if I choose different ESP32 board, I'm having same error for each ESP32 board.
If I choose an older library it does compile and load to the board but there's no sound at all at the DAC pin.
Maybe something changed on the espressif repository from Github.
Can anyone help?
I'll appreciate it your kind help.

**Comment by beer73** [comment]
Yeah, same problem here, please, someone to light the way.
Or tell us which version of esp32 and library has worked for you.
I use an ESP WROOM 32 DEVKITV1.

**Comment by beer73** [comment]
Ups, I downgraded the ESP32 library from 2.0.1 to 1.0.6 and all fine.
Sometimes these little things seem like mountains to newbies like me.

**Comment by rppsys** [comment]
This is the error:

    Compiling libraries...
    Compiling library "XT_DAC_Audio"
    
    (...)
    
    /home/arduino/libraries/XT_DAC_Audio/XT_DAC_Audio.cpp: In member function 'void XT_Instrument_Class::SetWaveForm(uint8_t)':
    /home/arduino/libraries/XT_DAC_Audio/XT_DAC_Audio.cpp:667:18: error: deleting object of polymorphic class type 'XT_Wave_Class' which has non-virtual destructor might cause undefined behaviour [-Werror=delete-non-virtual-dtor]
      delete (WaveForm);          // free any previous memory for a previous waveform
                      ^
    cc1plus: some warnings being treated as errors
    Usando biblioteca XT_DAC_Audio na pasta: /home/arduino/libraries/XT_DAC_Audio (legacy)
    exit status 1
    Erro compilando para a placa DOIT ESP32 DEVKIT V1

**Comment by syndicated-8** [comment]
I'm getting this error after freshly installing the XT_DAC_Audio library. This is for ESP32 WROOM 32S

In file included from C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/esp32s2/include/hal/include/hal/touch_sensor_types.h:11,
                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/esp32s2/include/esp_hw_support/include/esp_sleep.h:12,
                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32\cores\esp32/esp32-hal.h:33,
                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32\cores\esp32/esp32-hal-timer.h:23,
                 from C:\Users\DevEnv\Documents\Arduino\libraries\XT_DAC_Audio\Mixing\XT_DAC_Audio.cpp:23:
C:\Users\DevEnv\Documents\Arduino\libraries\XT_DAC_Audio\Mixing\XT_DAC_Audio.cpp: In function 'void onTimer()':
XT_DAC_Audio.cpp:155:31: error: 'RTC_IO_PAD_DAC1_REG' was not declared in this scope

**Comment by RobKeij** [comment]
Also here but I got more errors, to many to list here.
I'm trying to find the missing declarations etc.

**Comment by k1dbl4ck** [comment]
@syndicated-8 / @RobKeij 

`RTC_IO_PAD_DAC1_REG` (and other io registers) is declared in the esp32 soc headers....

Solve by adding `#include "soc/rtc_io_reg.h"` to the top of `XT_DAC_Audio.cpp`

**Comment by WeekendWarrior1** [comment]
> @syndicated-8 / @RobKeij
> 
> `RTC_IO_PAD_DAC1_REG` (and other io registers) is declared in the esp32 soc headers....
> 
> Solve by adding `#include "soc/rtc_io_reg.h"` to the top of `XT_DAC_Audio.cpp`

Thanks @k1dbl4ck, I have committed your fix.
